// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/life-os-dashboard/FocusMode.tsx": () => import("../components/mockups/life-os-dashboard/FocusMode.tsx"),
  "./components/mockups/life-os-dashboard/MissionControl.tsx": () => import("../components/mockups/life-os-dashboard/MissionControl.tsx"),
  "./components/mockups/life-os-dashboard/Momentum.tsx": () => import("../components/mockups/life-os-dashboard/Momentum.tsx")
};
